#!/usr/bin/python3

import sys

l_option = True
w_option = True
c_option = True

if len(sys.argv) > 1 and sys.argv[1][0] == '-':
	l_option = False
	w_option = False
	c_option = False

for arg in sys.argv:
	if arg[0] == '-':
		if 'l' in arg:
			l_option = True
		if 'w' in arg:
			w_option = True
		if 'c' in arg:
			c_option = True
		
	files = [i for i in range(1,len(sys.argv)) if sys.argv[1][0] != '-']

if l_option == True:
	eggs = 'spam'
print(l_option, w_option, c_option, files)


