#!/usr/bin/python3

import sys

if ('l' or 'w' or 'c') not in arg:
	l_option = True
	w_option = True
	c_ option = True

elif argv[1][0] == '-':
	if 'l' in arg:
		l_option = True

	elif 'w' in arg:
		w_option = True

	elif 'c' in arg:
		c_option = True

