#!/usr/bin/python3

import sys

l_option = True
w_option = True
c_option = True

if len(sys.argv) > 1 and sys.argv[1][0] == '-':
	l_option = False
	w_option = False
	c_option = False
else:
	raise AttributeError('The command is incomplete')

for arg in sys.argv:
	if arg[0] == '-':
		if 'l' in arg:
			l_option = True
		elif 'w' in arg:
			w_option = True
		elif 'c' in arg:
			c_option = True
		else:
			raise AttributeError('That command is not available')



